package util

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The committed fixture pair, mirrored into internal/agents/hunt/testdata by
// go/scripts/gen_golden.py. See that script's GRAPH_CONTEXT_CASES for the
// Python side of every golden asserted here.
const (
	fixtureGraph       = "testdata/fixture/graph.json"
	fixtureInventory   = "testdata/fixture/inventory.json"
	fixtureNotAnObject = "testdata/fixture/not_an_object.json"
	fixtureAbsent      = "testdata/fixture/absent.json" // deliberately does not exist
)

func readGolden(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "golden", name))
	if err != nil {
		t.Fatalf("reading golden %s: %v (regenerate with go/scripts/gen_golden.py)", name, err)
	}
	return string(b)
}

// TestBuildGraphContextForHunter_MatchesThePythonGoldens is the byte-for-byte
// parity gate: every case here is generated by driving the REAL Python
// build_graph_context_for_hunter over the same committed fixture (see
// GRAPH_CONTEXT_CASES in go/scripts/gen_golden.py), so a golden can only move
// when the Python function moves.
func TestBuildGraphContextForHunter_MatchesThePythonGoldens(t *testing.T) {
	cases := []struct {
		name      string
		graph     string
		inventory string
		keywords  []string
	}{
		{"iam", fixtureGraph, fixtureInventory, []string{"iam", "role", "policy"}},
		{"data", fixtureGraph, fixtureInventory, []string{"s3", "bucket", "kms"}},
		{"all", fixtureGraph, fixtureInventory, []string{""}},
		{"nomatch", fixtureGraph, fixtureInventory, []string{"nonexistent_type_xyz"}},
		{"missing_files", fixtureAbsent, fixtureAbsent, []string{"iam"}},
		{"not_an_object", fixtureNotAnObject, fixtureNotAnObject, []string{"iam"}},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			nodes, stats, edges := BuildGraphContextForHunter(tc.graph, tc.inventory, tc.keywords)
			for _, part := range []struct {
				label, got, golden string
			}{
				{"nodes", nodes, tc.name + "_nodes.txt"},
				{"stats", stats, tc.name + "_stats.txt"},
				{"edges", edges, tc.name + "_edges.txt"},
			} {
				if want := readGolden(t, part.golden); part.got != want {
					t.Errorf("%s block differs from Python\n--- got ---\n%s\n--- want ---\n%s",
						part.label, part.got, want)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// tests/test_graph_context.py, ported.
//
// THE PYTHON FILE IS STALE: it calls
// build_graph_context_for_hunter(graph, inventory, keywords) with pydantic
// MODELS, and imports ResourceNode/ResourceEdge/ResourceCluster, all of which
// were removed. The function has taken (graph_path, inventory_path, keywords)
// and read JSON files for some time, so the module does not import. Each test
// below therefore keeps the Python ASSERTION and re-expresses the SETUP against
// the current signature, using the committed fixture in place of the models the
// Python test built.
// ---------------------------------------------------------------------------

func TestBuildGraphContext_IAMKeywordsFilter(t *testing.T) {
	summary, _, edges := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"iam", "role"})
	mustContain(t, "summary", summary, "aws_iam_role.admin")
	mustNotContain(t, "summary", summary, "aws_s3_bucket.data")
	mustContain(t, "edges", edges, "aws_iam_role.admin")
}

func TestBuildGraphContext_NetworkKeywordsFilter(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"vpc", "subnet"})
	mustContain(t, "summary", summary, "aws_vpc.main")
	mustNotContain(t, "summary", summary, "aws_iam_role.admin")
}

func TestBuildGraphContext_S3KeywordsReturnBucket(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"s3", "bucket"})
	mustContain(t, "summary", summary, "aws_s3_bucket.data")
}

func TestBuildGraphContext_EmptyKeywordMatchesAll(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{""})
	for _, id := range []string{
		"aws_iam_role.admin", "aws_iam_policy.broad", "aws_s3_bucket.data",
		"aws_vpc.main", "aws_subnet.private", "aws_instance.web",
		"aws_kms_key.master", "aws_cloudtrail.audit", "aws_secretsmanager_secret.db",
	} {
		mustContain(t, "summary", summary, id)
	}
}

func TestBuildGraphContext_NoMatchReturnsNoneMessage(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"nonexistent_type_xyz"})
	mustContain(t, "summary", summary, "none matched")
}

func TestBuildGraphContext_InventoryStatsFormat(t *testing.T) {
	_, stats, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"iam"})
	// The fixture inventory lists 12 resources while the graph holds 9 nodes:
	// the two counts come from DIFFERENT documents and must not be conflated.
	for _, want := range []string{
		"Total resources: 12", "Graph nodes: 9", "Graph edges: 4",
		"Modules: 2", "Variables: 2", "Outputs: 1",
		"Filtered nodes: 2", "Filtered edges: 1",
	} {
		mustContain(t, "stats", stats, want)
	}
}

func TestBuildGraphContext_EdgeIncludesConnectedEdges(t *testing.T) {
	// An edge counts as relevant when EITHER endpoint is in the domain, so the
	// data domain pulls in the instance->key edge whose source is outside it,
	// and the instance then shows up as a 1-hop neighbor.
	summary, _, edges := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"s3", "bucket", "kms"})
	mustContain(t, "edges", edges, "encrypted_by")
	mustContain(t, "edges", edges, "aws_instance.web")
	mustContain(t, "summary", summary, "CONNECTED RESOURCES (1-hop neighbors):")
	mustContain(t, "summary", summary, "aws_instance.web")
}

func TestBuildGraphContext_ConfigSummaryInOutput(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"iam"})
	mustContain(t, "summary", summary, "AdministratorAccess")
}

func TestBuildGraphContext_EmptyGraph(t *testing.T) {
	// Python built empty models; the current signature reaches the same state
	// through the `except Exception` fallback on an unreadable path.
	summary, stats, edges := BuildGraphContextForHunter(fixtureAbsent, fixtureAbsent, []string{"iam"})
	mustContain(t, "summary", summary, "none matched")
	mustContain(t, "stats", stats, "Total resources: 0")
	mustContain(t, "edges", edges, "no edges matched")
}

// ---------------------------------------------------------------------------
// Behaviors the (stale) Python tests never covered but the prompt text depends
// on. Each one is pinned by the Python-generated goldens above as well; these
// name the rule so a failure says WHAT broke.
// ---------------------------------------------------------------------------

// The graph builder writes config_summary as a dict, so the f-string renders a
// CPython dict repr — single quotes, None/True/False, and the .tf file's key
// order, NOT alphabetical order.
func TestBuildGraphContext_ConfigSummaryIsAPythonDictRepr(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"aws_iam_policy"})
	const want = "    Config: {'policy': '{\"Statement\":[{\"Action\":\"*\",\"Resource\":\"*\"}]}', 'description': None}"
	mustContain(t, "summary", summary, want)
}

func TestBuildGraphContext_ConfigSummaryKeyOrderIsNotSorted(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"aws_iam_role"})
	// Sorted order would be assume_role_policy, managed_policy_arns, name.
	const want = "    Config: {'name': 'admin', 'assume_role_policy': "
	mustContain(t, "summary", summary, want)
}

func TestBuildGraphContext_NestedValuesUsePythonRepr(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"aws_kms_key"})
	// bool -> False, int -> 7, float -> 90.0 (not 90), non-ASCII kept verbatim.
	const want = "    Config: {'enable_key_rotation': False, 'deletion_window_in_days': 7, " +
		"'rotation_period_days': 90.0, 'description': 'clé principale'}"
	mustContain(t, "summary", summary, want)
}

// `edge.get("type", "references")` — the only .get in the edge block with a
// default, and the fixture's last edge has no "type".
func TestBuildGraphContext_EdgeTypeDefaultsToReferences(t *testing.T) {
	_, _, edges := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"aws_instance"})
	mustContain(t, "edges", edges, "  - aws_instance.web --[references]--> aws_kms_key.master")
}

// `if edge.get("description")` — an ABSENT or EMPTY description emits no line.
func TestBuildGraphContext_FalsyEdgeDescriptionEmitsNoLine(t *testing.T) {
	_, _, edges := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"s3", "bucket", "kms"})
	lines := strings.Split(edges, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "    ") {
			t.Errorf("no description line expected, got %q\nfull block:\n%s", line, edges)
		}
	}
	// …and a truthy one does emit.
	_, _, iamEdges := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"iam"})
	mustContain(t, "edges", iamEdges, "\n    Admin role has the broad policy attached")
}

// The "\n" that Python puts INSIDE the CONNECTED RESOURCES header becomes a
// blank separator line after "\n".join.
func TestBuildGraphContext_BlankLineBeforeTheNeighborBlock(t *testing.T) {
	summary, _, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"s3", "bucket", "kms"})
	mustContain(t, "summary", summary, "\n\nCONNECTED RESOURCES (1-hop neighbors):\n")
}

// A readable file that is not a JSON OBJECT takes the second fallback (the
// isinstance re-check), which is a different branch from the `except`.
func TestBuildGraphContext_NonObjectDocumentFallsBackToTheDefault(t *testing.T) {
	summary, stats, edges := BuildGraphContextForHunter(fixtureNotAnObject, fixtureNotAnObject, []string{"iam"})
	mustContain(t, "summary", summary, "none matched")
	mustContain(t, "edges", edges, "no edges matched")
	mustContain(t, "stats", stats, "Providers: none")
	mustContain(t, "stats", stats, "Graph nodes: 0")
}

// sorted({r["provider"] for r in resources if r["provider"]}) — dedup, sort,
// and drop the falsy ones ("" and null in the fixture).
func TestBuildGraphContext_ProvidersAreDedupedSortedAndFiltered(t *testing.T) {
	_, stats, _ := BuildGraphContextForHunter(fixtureGraph, fixtureInventory, []string{"iam"})
	mustContain(t, "stats", stats, "\nProviders: aws, google\n")
}

// Every .get in the node block is defaultless, so absent keys print as Python's
// None.
func TestBuildGraphContext_AbsentNodeFieldsRenderAsNone(t *testing.T) {
	dir := t.TempDir()
	graph := filepath.Join(dir, "graph.json")
	writeFile(t, graph, `{"nodes": [{"resource_type": "aws_iam_role"}], "edges": []}`)

	summary, stats, _ := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
	mustContain(t, "summary", summary, "  - None (aws_iam_role) @ None")
	mustContain(t, "summary", summary, "    Config: None")
	mustContain(t, "stats", stats, "Filtered nodes: 1")
}

// Non-dict entries inside "nodes"/"edges" are skipped by the isinstance guards,
// but the COUNTS in the stats block come from the raw lists, so the two
// disagree on purpose.
func TestBuildGraphContext_NonDictEntriesAreSkippedButStillCounted(t *testing.T) {
	dir := t.TempDir()
	graph := filepath.Join(dir, "graph.json")
	writeFile(t, graph, `{"nodes": ["oops", {"resource_id": "a", "resource_type": "aws_iam_role"}],
	                      "edges": [42, {"source": "a", "target": "b"}]}`)

	summary, stats, edges := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
	mustContain(t, "summary", summary, "  - a (aws_iam_role) @ None")
	mustNotContain(t, "summary", summary, "oops")
	mustContain(t, "edges", edges, "  - a --[references]--> b")
	mustContain(t, "stats", stats, "Graph nodes: 2")
	mustContain(t, "stats", stats, "Graph edges: 2")
	mustContain(t, "stats", stats, "Filtered nodes: 1")
	mustContain(t, "stats", stats, "Filtered edges: 1")
}

// A "nodes" key that is not a list is ignored for filtering but still measured
// by len() for the stats line — Python reads graph_data["nodes"] twice, once
// guarded and once not.
func TestBuildGraphContext_NonListNodesAreIgnoredButLenIsStillTaken(t *testing.T) {
	dir := t.TempDir()
	graph := filepath.Join(dir, "graph.json")
	writeFile(t, graph, `{"nodes": {"a": 1, "b": 2}, "edges": []}`)

	summary, stats, _ := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
	mustContain(t, "summary", summary, "none matched")
	mustContain(t, "stats", stats, "Graph nodes: 2") // len({"a":1,"b":2}) == 2
	mustContain(t, "stats", stats, "Filtered nodes: 0")
}

// The neighbor block is the one place Python iterates a set. Go emits
// first-encounter order; assert it is STABLE and follows the edge scan
// (source before target, edges in document order).
func TestBuildGraphContext_NeighborOrderIsDeterministic(t *testing.T) {
	dir := t.TempDir()
	graph := filepath.Join(dir, "graph.json")
	writeFile(t, graph, `{"nodes": [
	    {"resource_id": "hub", "resource_type": "aws_iam_role"},
	    {"resource_id": "zeta", "resource_type": "aws_s3_bucket"},
	    {"resource_id": "alpha", "resource_type": "aws_s3_bucket"},
	    {"resource_id": "mid", "resource_type": "aws_s3_bucket"}
	  ], "edges": [
	    {"source": "zeta", "target": "hub"},
	    {"source": "hub", "target": "alpha"},
	    {"source": "mid", "target": "hub"}
	  ]}`)

	first, _, _ := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
	want := strings.Join([]string{
		"RELEVANT RESOURCES:",
		"  - hub (aws_iam_role) @ None",
		"    Config: None",
		"",
		"CONNECTED RESOURCES (1-hop neighbors):",
		"  - zeta (aws_s3_bucket) @ None",
		"    Config: None",
		"  - alpha (aws_s3_bucket) @ None",
		"    Config: None",
		"  - mid (aws_s3_bucket) @ None",
		"    Config: None",
	}, "\n")
	if first != want {
		t.Fatalf("neighbor block\n--- got ---\n%s\n--- want ---\n%s", first, want)
	}
	for i := 0; i < 50; i++ {
		again, _, _ := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
		if again != first {
			t.Fatalf("neighbor order is not stable across runs:\n%s\nvs\n%s", first, again)
		}
	}
}

// A neighbor id with no node of its own is dropped by
// `if nid in all_nodes_by_id`.
func TestBuildGraphContext_UnknownNeighborIDsAreDropped(t *testing.T) {
	dir := t.TempDir()
	graph := filepath.Join(dir, "graph.json")
	writeFile(t, graph, `{"nodes": [{"resource_id": "hub", "resource_type": "aws_iam_role"}],
	                      "edges": [{"source": "hub", "target": "ghost"}]}`)

	summary, _, edges := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
	mustNotContain(t, "summary", summary, "CONNECTED RESOURCES")
	mustContain(t, "edges", edges, "  - hub --[references]--> ghost")
}

// The two id lookups use DIFFERENT defaults: all_nodes_by_id keys on
// node.get("resource_id", "") while relevant_node_ids collects
// node.get("resource_id") — Python None. An id-less node therefore lands under
// "" in the map and under None in the set, and an edge with no "source" reads
// as None in the relevance filter but as "" in the neighbor loop. The observable
// consequence: the id-less node is pulled in as its own 1-hop neighbor.
func TestBuildGraphContext_MissingIDDefaultsDifferInTheMapAndTheSet(t *testing.T) {
	dir := t.TempDir()
	graph := filepath.Join(dir, "graph.json")
	writeFile(t, graph, `{"nodes": [{"resource_type": "aws_iam_role", "file_path": "iam.tf"}],
	                      "edges": [{"target": "unrelated"}]}`)

	summary, stats, edges := BuildGraphContextForHunter(graph, fixtureAbsent, []string{"iam"})
	// The edge has no "source": edge.get("source") is None, which IS in
	// relevant_node_ids, so the edge is relevant.
	mustContain(t, "stats", stats, "Filtered edges: 1")
	mustContain(t, "edges", edges, "  - None --[references]--> unrelated")
	// In the neighbor loop the same endpoint reads as "" (not in the set), and
	// "" IS a key of all_nodes_by_id — so the node reappears as a neighbor.
	mustContain(t, "summary", summary, "CONNECTED RESOURCES (1-hop neighbors):")
	if got := strings.Count(summary, "  - None (aws_iam_role) @ iam.tf"); got != 2 {
		t.Errorf("expected the id-less node listed twice (relevant + neighbor), got %d\n%s", got, summary)
	}
}

// ---------------------------------------------------------------------------

func mustContain(t *testing.T, label, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("%s block does not contain %q\n--- block ---\n%s", label, needle, haystack)
	}
}

func mustNotContain(t *testing.T, label, haystack, needle string) {
	t.Helper()
	if strings.Contains(haystack, needle) {
		t.Errorf("%s block unexpectedly contains %q\n--- block ---\n%s", label, needle, haystack)
	}
}

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}
