// Package harnessx is the single choke-point every cloudsecurity-af agent uses
// to call the AgentField harness for structured output.
//
// It replaces two Python mechanisms at once:
//
//   - `await app.harness(prompt, schema=Model, cwd=..., project_dir=...)` —
//     Run[T] supplies the JSON schema and the typed destination.
//   - `extract_harness_result(result, Model, agent_name)` from
//     src/cloudsecurity_af/agents/_utils.py — Extract[T] reproduces its error
//     classification, its stdout diagnostics and its exact error strings.
//
// RunExtract[T] is the two of them together, which is what every agent file in
// this repo actually does.
//
// SCHEMA RESOLUTION. The Go SDK does not merely pretty-print the schema into the
// prompt: it VALIDATES every parsed output against it with
// santhosh-tekuri/jsonschema/v5 (harness/runner.go -> runSchemaValidation) and
// drives its schema-retry loop off validation failures. So the schema has to
// match Python's, or Python-valid model output gets rejected. SchemaFor[T]
// therefore prefers the COMMITTED pydantic fixture — generated by
// go/scripts/gen_schemas.py from the very model the Python agent passes — and
// only falls back to invopop reflection for types with no fixture.
//
// DIVERGENCE (documented, go/README.md item 7) — KEY ORDER, NOT CONTENT. The
// schema CONTENT matches Python's; its key ORDER does not, and cannot from
// here. Python appends `json.dumps(model_json_schema(), indent=2)` to the
// prompt, which keeps pydantic's field declaration order. Go's path is a
// `map[string]any` end to end — this file decodes the fixture into one, and the
// SDK renders it with `json.MarshalIndent`, which SORTS map keys — so the
// prompt's schema block is alphabetised. Both `agent.Harness` and
// `harness.BuildPromptSuffix` take a `map[string]any`, so an order-preserving
// schema type would have to come from the SDK. The content is unaffected, and
// so is the byte length that decides the SDK's large-schema branch — for
// HuntResult both renderings are 4174 bytes (a 199-line reordering diff),
// which is why LoadEmbeddedSchema's UseNumber decode matters: without it
// pydantic's `"default": 0.0` would render as `0` and the two would differ in
// content too.
//
// DIVERGENCE (documented, go/README.md item 8) — SCALAR STRICTNESS. Python
// validates the parsed harness output with `schema.model_validate(data)`, i.e.
// pydantic's LAX mode, so `"iac_line": "12"` is accepted on the first attempt.
// The SDK validates with a plain `json.Unmarshal` PLUS this fixture, and both
// reject it, so the schema-retry budget burns and the agent ends as a harness
// error. `internal/afx/lax.go` closes the same gap everywhere the port owns the
// bind; closing it here needs a change in sdk/go/harness.
//
// Unlike the pr-af port this is adapted from, there is NO RegisterSchema
// registry: a fixture is resolved by the Go destination type's NAME, i.e.
// testdata/schemas/<reflect.TypeOf(T).Name()>.json. That works because the port
// contract requires Go struct names to equal the pydantic class names exactly,
// and it removes a whole class of "forgot to register" bugs — adding a model
// means running gen_schemas.py and nothing else.
package harnessx

import (
	"bytes"
	"embed"
	"encoding/json"
	"reflect"
	"sync"

	"github.com/invopop/jsonschema"
)

// embeddedSchemas holds the committed pydantic-generated JSON schemas, one per
// destination type that flows through Run[T]. They are produced by
// go/scripts/gen_schemas.py; see that script for the enumerated `schema=` call
// sites they cover.
//
// The embed directive skips files whose names begin with "_" or "." unless the
// pattern uses the all: prefix, so every fixture basename is plain.
//
//go:embed testdata/schemas/*.json
var embeddedSchemas embed.FS

// schemaCache memoizes the resolved schema map per concrete type T, so the
// fixture decode (or the non-trivial invopop reflection) runs once per type.
// The stored map is treated as immutable by every caller — the harness only
// marshals and reads it — so sharing it across goroutines is safe.
var schemaCache sync.Map // reflect.Type -> map[string]any

// SchemaFor returns the JSON-schema map the Go SDK harness consumes for T:
// the committed pydantic fixture named after T when one exists, otherwise an
// invopop reflection of T.
//
// It is exported because internal/aix needs the same schema for the `.ai(...)`
// structured-output path (where it is additionally strictified for OpenAI).
func SchemaFor[T any]() map[string]any {
	return schemaForType(reflect.TypeOf((*T)(nil)).Elem())
}

// schemaForType is SchemaFor's non-generic core, so the drift test can iterate
// over reflect.Types.
func schemaForType(t reflect.Type) map[string]any {
	if cached, ok := schemaCache.Load(t); ok {
		return cached.(map[string]any)
	}

	var m map[string]any
	if name := fixtureName(t); name != "" {
		// A load failure "cannot happen" for a committed fixture (go:embed
		// compiles it in and gen_schemas.py emits valid JSON), but if it ever
		// did we fall through to invopop rather than panic.
		if loaded, err := LoadEmbeddedSchema(name); err == nil {
			m = loaded
		}
	}
	if m == nil {
		m = reflectSchema(t)
	}

	schemaCache.Store(t, m)
	return m
}

// fixtureName is the fixture basename for a destination type: its bare Go type
// name, which the port contract keeps equal to the pydantic class name.
// Anonymous types (and pointers/slices, which are never Run[T] destinations)
// have no name and get the reflection fallback.
func fixtureName(t reflect.Type) string {
	return t.Name()
}

// LoadEmbeddedSchema decodes a committed schema fixture by basename (no
// extension). Exported for the fixture tests and for the schemas package's
// cross-check.
//
// The decode uses UseNumber, which is load-bearing for PROMPT TEXT. pydantic
// writes a `float` default as `0.0` (HuntResult.hunt_duration_seconds,
// VerifiedFinding.risk_score), and Python appends the schema to the prompt with
// json.dumps, keeping that spelling. A plain decode turns `0.0` into float64(0)
// and json.MarshalIndent — which is how the SDK renders this map into the
// prompt — writes it back as `0`, changing the prompt. json.Number carries the
// literal through both hops verbatim. It is also what the SDK's jsonschema
// validation sees, and json.Number marshals verbatim there too.
func LoadEmbeddedSchema(name string) (map[string]any, error) {
	b, err := embeddedSchemas.ReadFile("testdata/schemas/" + name + ".json")
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.UseNumber()
	var m map[string]any
	if err := dec.Decode(&m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmbeddedSchemaNames lists every committed fixture basename, sorted by
// embed.FS's own (lexical) directory order. Used by the fixture tests and by
// the schemas package's parity test.
func EmbeddedSchemaNames() []string {
	entries, err := embeddedSchemas.ReadDir("testdata/schemas")
	if err != nil {
		return nil
	}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if len(name) > 5 && name[len(name)-5:] == ".json" {
			out = append(out, name[:len(name)-5])
		}
	}
	return out
}

// reflectSchema is the invopop fallback for types with no committed fixture.
//
// Reflector configuration (kept identical to the pr-af port so the two behave
// the same for ad-hoc types):
//   - ExpandedStruct: inline the root type's own properties at the top level so
//     map["properties"] is populated for the SDK's DiagnoseOutputFailure.
//   - DoNotReference=false (default): emit a $defs map for nested struct types.
//   - Anonymous: suppress the auto-generated $id derived from the package path.
func reflectSchema(t reflect.Type) map[string]any {
	r := &jsonschema.Reflector{
		ExpandedStruct: true,  // root properties inline at top level
		DoNotReference: false, // emit $defs for nested types
		Anonymous:      true,  // no auto-generated $id from PkgPath
	}
	schema := r.ReflectFromType(t)

	b, err := json.Marshal(schema)
	if err != nil {
		return map[string]any{}
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return map[string]any{}
	}
	return m
}
