package schemas

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"testing"
	"time"

	"github.com/Agent-Field/cloudsecurity-af/go/internal/scoring"
)

// This file is the exhaustive model-parity test the port contract requires:
// for EVERY pydantic model, the Go constructor's marshaled JSON must have the
// same key set AND the same default values as
// `Model(**minimal_required).model_dump()` in Python.
//
// The ground truth lives in testdata/model_keys.json, generated by
// go/scripts/gen_model_keys.py against
// ~/.agentfield/packages/cloudsecurity-af/venv/bin/python. Regenerate it
// whenever a Python schema changes; a Go/Python drift fails here first.

// pythonModel is one entry of testdata/model_keys.json.
type pythonModel struct {
	Module           string          `json:"module"`
	Keys             []string        `json:"keys"`
	Dump             json.RawMessage `json:"dump"`
	Nondeterministic []string        `json:"nondeterministic"`
}

// fixedTimestamp mirrors gen_model_keys.py FIXED_TS — the timestamp the fixture
// pins for CloudSecurityScanResult, so that key can be compared by value.
var fixedTimestamp = NewTimestamp(time.Date(2026, 1, 2, 3, 4, 5, 123456000, time.UTC))

// goDefaults returns, for every model name in the fixture, the Go value that
// must reproduce the Python default vector.
//
// The two entries that pass extra arguments do so because gen_model_keys.py
// passes the same ones: VerifiedFinding's verdict/severity are REQUIRED with no
// pydantic default, and CloudSecurityScanResult's timestamp likewise.
func goDefaults() map[string]any {
	verified := NewVerifiedFinding()
	verified.Verdict = VerdictConfirmed
	verified.Severity = scoring.SeverityMedium

	scanResult := NewCloudSecurityScanResult()
	scanResult.Timestamp = fixedTimestamp

	return map[string]any{
		// schemas/recon.py
		"Variable":          NewVariable(),
		"Output":            NewOutput(),
		"ProviderConfig":    NewProviderConfig(),
		"Module":            NewModule(),
		"Resource":          NewResource(),
		"ResourceInventory": NewResourceInventory(),
		"ResourceGraph":     NewResourceGraph(),
		"ConfigDiff":        NewConfigDiff(),
		"DriftedResource":   NewDriftedResource(),
		"DriftReport":       NewDriftReport(),
		"ReconResult":       NewReconResult(),
		// schemas/hunt.py
		"AffectedResource": NewAffectedResource(),
		"RawFinding":       NewRawFinding(),
		"HuntResult":       NewHuntResult(),
		// schemas/chain.py
		"AttackStep":  NewAttackStep(),
		"BlastRadius": NewBlastRadius(),
		"AttackPath":  NewAttackPath(),
		"ChainResult": NewChainResult(),
		// schemas/prove.py
		"Proof":                 NewProof(),
		"IaCDiff":               NewIaCDiff(),
		"RemediationSuggestion": NewRemediationSuggestion(),
		"VerifiedFinding":       verified,
		// schemas/input.py
		"CloudConfig":        NewCloudConfig(),
		"CloudSecurityInput": NewCloudSecurityInput(),
		// schemas/output.py
		"CloudSecurityScanResult": scanResult,
		"ScanProgress":            NewScanProgress(),
		"ScanMetrics":             NewScanMetrics(),
		// schemas/views.py
		"FindingForDedup":  NewFindingForDedup(),
		"FindingForProver": NewFindingForProver(),
		"FindingForChain":  NewFindingForChain(),
		// agents/chain/path_constructor.py
		"ChildInvestigation":    NewChildInvestigation(),
		"PathInvestigationPlan": NewPathInvestigationPlan(),
	}
}

func loadPythonModels(t *testing.T) map[string]pythonModel {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "model_keys.json"))
	if err != nil {
		t.Fatalf("read testdata/model_keys.json: %v (regenerate with scripts/gen_model_keys.py)", err)
	}
	var models map[string]pythonModel
	if err := json.Unmarshal(raw, &models); err != nil {
		t.Fatalf("decode testdata/model_keys.json: %v", err)
	}
	return models
}

// TestModelCoverage guards that the Go side has an entry for every pydantic
// model and no stale extras. It is the test that fails when someone adds a
// model to Python (or to this package) and forgets the other side.
func TestModelCoverage(t *testing.T) {
	python := loadPythonModels(t)
	golang := goDefaults()

	for name := range python {
		if _, ok := golang[name]; !ok {
			t.Errorf("pydantic model %q (%s) has no Go constructor registered in goDefaults()", name, python[name].Module)
		}
	}
	for name := range golang {
		if _, ok := python[name]; !ok {
			t.Errorf("Go model %q is not in testdata/model_keys.json — add it to scripts/gen_model_keys.py MODELS", name)
		}
	}
	if len(python) != 32 {
		t.Errorf("fixture holds %d models, expected 32 (7 schemas/*.py modules + path_constructor.py)", len(python))
	}
}

// TestModelKeySets asserts the marshaled key SET of every Go constructor equals
// Python's model_dump().keys() exactly. This is what enforces "no omitempty
// anywhere": a single omitempty tag would drop a zero-valued key and fail here.
func TestModelKeySets(t *testing.T) {
	python := loadPythonModels(t)
	for name, value := range goDefaults() {
		want, ok := python[name]
		if !ok {
			continue // reported by TestModelCoverage
		}
		t.Run(name, func(t *testing.T) {
			raw, err := json.Marshal(value)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			var got map[string]json.RawMessage
			if err := json.Unmarshal(raw, &got); err != nil {
				t.Fatalf("re-decode: %v", err)
			}
			gotKeys := make([]string, 0, len(got))
			for k := range got {
				gotKeys = append(gotKeys, k)
			}
			wantKeys := append([]string(nil), want.Keys...)
			sort.Strings(gotKeys)
			sort.Strings(wantKeys)
			if !reflect.DeepEqual(gotKeys, wantKeys) {
				t.Errorf("json key set mismatch\n go:     %v\n python: %v", gotKeys, wantKeys)
			}
		})
	}
}

// TestModelDefaultValues asserts every default VALUE matches Python's, key by
// key. This is what pins "terraform", ["us-east-1"], "moderate", "medium",
// "static", Severity.HIGH, the empty-slice-vs-null rule, and the empty maps.
func TestModelDefaultValues(t *testing.T) {
	python := loadPythonModels(t)
	for name, value := range goDefaults() {
		want, ok := python[name]
		if !ok {
			continue
		}
		t.Run(name, func(t *testing.T) {
			gotRaw, err := json.Marshal(value)
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			var gotMap, wantMap map[string]any
			if err := json.Unmarshal(gotRaw, &gotMap); err != nil {
				t.Fatalf("decode go json: %v", err)
			}
			if err := json.Unmarshal(want.Dump, &wantMap); err != nil {
				t.Fatalf("decode python dump: %v", err)
			}
			skip := make(map[string]bool, len(want.Nondeterministic))
			for _, k := range want.Nondeterministic {
				skip[k] = true
			}
			for key, wantVal := range wantMap {
				if skip[key] {
					continue
				}
				gotVal, present := gotMap[key]
				if !present {
					t.Errorf("key %q missing from Go output", key)
					continue
				}
				if !reflect.DeepEqual(gotVal, wantVal) {
					gj, _ := json.Marshal(gotVal)
					wj, _ := json.Marshal(wantVal)
					t.Errorf("key %q: go=%s python=%s", key, gj, wj)
				}
			}
		})
	}
}

var uuid4Pattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

// TestUUIDDefaultedFields checks that every field the fixture marks
// nondeterministic is seeded with a well-formed, unique RFC 4122 v4 string —
// the Go equivalent of `default_factory=lambda: str(uuid4())`.
func TestUUIDDefaultedFields(t *testing.T) {
	python := loadPythonModels(t)
	seen := map[string]bool{}
	total := 0
	for name, value := range goDefaults() {
		want, ok := python[name]
		if !ok || len(want.Nondeterministic) == 0 {
			continue
		}
		raw, err := json.Marshal(value)
		if err != nil {
			t.Fatalf("%s: marshal: %v", name, err)
		}
		var got map[string]any
		if err := json.Unmarshal(raw, &got); err != nil {
			t.Fatalf("%s: decode: %v", name, err)
		}
		for _, key := range want.Nondeterministic {
			s, isStr := got[key].(string)
			if !isStr {
				t.Errorf("%s.%s = %v, want a uuid4 string", name, key, got[key])
				continue
			}
			if !uuid4Pattern.MatchString(s) {
				t.Errorf("%s.%s = %q, not an RFC 4122 v4 uuid", name, key, s)
			}
			if seen[s] {
				t.Errorf("%s.%s = %q collides with another defaulted field", name, key, s)
			}
			seen[s] = true
			total++
		}
	}
	// AttackPath.id, RawFinding.{id,fingerprint}, VerifiedFinding.{id,fingerprint}
	if total != 5 {
		t.Errorf("checked %d uuid-defaulted fields, expected 5", total)
	}
}
