package recon

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/Agent-Field/cloudsecurity-af/go/internal/pyfmt"
)

// VALIDATION CONTRACT for ParseTerraformDirectory (from parse_terraform_directory
// in src/cloudsecurity_af/agents/recon/_terraform_parser.py, expressed in terms
// of observable behavior rather than of the Go code):
//
//  1. Every *.tf under the repo is parsed, in pathlib sort order, and its path is
//     recorded RELATIVE to the repo.
//  2. `resource` blocks with >=2 labels produce {id "<type>.<name>", type, name,
//     provider, file_path, line_number 0, config, references, referenced_by};
//     `data` blocks produce the same with id "data.<type>.<name>" and type
//     "data.<type>".
//  3. `variable`, `output`, `provider` and `module` blocks produce their own
//     records with the exact key sets Python emits, including the str()-vs-raw
//     asymmetries (variable.type/default are str()-ed, variable.description is
//     not; output.value is str()-ed with "" for a missing value;
//     provider.version is ALWAYS null).
//  4. `provider` is _PROVIDER_MAP[type prefix] or the prefix itself.
//  5. `references` is the sorted, de-duplicated set of resource-shaped tokens
//     found in any string in the config, minus the var./local./each./self./
//     count./path./terraform. namespaces. `referenced_by` is its reverse index.
//  6. The file is inventory.json inside output_dir, written as
//     json.dump(..., indent=2, default=str).
//  7. An unparsable file is skipped, not fatal.
//  8. The return value is (path, len(resources), "terraform").
//
// The fixtures the assertions run against are generated by
// go/scripts/gen_golden.py from the REAL Python parser.

const (
	pythonInventoryFixture  = "testdata/python/inventory.json"
	pythonExpressionsFixt   = "testdata/python/expressions_inventory.json"
	pythonSummaryFixture    = "testdata/python/summary.json"
	vulnerableInfraFixture  = "testdata/vulnerable_infra"
	expressionsFixtureDir   = "testdata/expressions"
	pyhcl2ReprMarker        = "SourceSpan("
	pythonTreeInfraRelative = "../../../../tests/fixtures/vulnerable_infra/main.tf"
)

// parseFixture runs the Go parser over dir and returns the decoded inventory.
func parseFixture(t *testing.T, dir string) (inv pyfmt.Ordered, path string, total int, iacType string) {
	t.Helper()
	out := t.TempDir()
	path, total, iacType, err := ParseTerraformDirectory(dir, out)
	if err != nil {
		t.Fatalf("ParseTerraformDirectory(%q): %v", dir, err)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	decoded, err := pyfmt.Load(raw)
	if err != nil {
		t.Fatalf("decoding %s: %v", path, err)
	}
	obj, ok := decoded.(pyfmt.Ordered)
	if !ok {
		t.Fatalf("inventory.json decoded as %T, want an object", decoded)
	}
	return obj, path, total, iacType
}

func loadPythonFixture(t *testing.T, rel string) pyfmt.Ordered {
	t.Helper()
	raw, err := os.ReadFile(rel)
	if err != nil {
		t.Fatalf("reading %s (regenerate with go/scripts/gen_golden.py): %v", rel, err)
	}
	decoded, err := pyfmt.Load(raw)
	if err != nil {
		t.Fatalf("decoding %s: %v", rel, err)
	}
	obj, ok := decoded.(pyfmt.Ordered)
	if !ok {
		t.Fatalf("%s decoded as %T, want an object", rel, decoded)
	}
	return obj
}

// Contract items 6 and 8.
func TestParseTerraformDirectory_ReturnValuesAndFileLocation(t *testing.T) {
	out := t.TempDir()
	path, total, iacType, err := ParseTerraformDirectory(vulnerableInfraFixture, out)
	if err != nil {
		t.Fatalf("ParseTerraformDirectory: %v", err)
	}

	summary := loadPythonFixture(t, pythonSummaryFixture)
	wantTotal, _ := summary.Get("total_resources")
	wantType, _ := summary.Get("iac_type")

	if total != wantTotal {
		t.Errorf("total_resources = %d, Python says %v", total, wantTotal)
	}
	if iacType != wantType {
		t.Errorf("iac_type = %q, Python says %v", iacType, wantType)
	}
	if want := filepath.Join(out, "inventory.json"); path != want {
		t.Errorf("path = %q, want %q", path, want)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("inventory.json was not written: %v", err)
	}
}

// Contract items 1-4 and 6: everything except the expression rendering must be
// identical to what the Python parser produced for the same fixture.
func TestParseTerraformDirectory_MatchesPythonOnVulnerableInfra(t *testing.T) {
	got, _, _, _ := parseFixture(t, vulnerableInfraFixture)
	want := loadPythonFixture(t, pythonInventoryFixture)

	assertSameKeyOrder(t, "$", got, want)

	gotRes := sectionOf(t, got, "resources")
	wantRes := sectionOf(t, want, "resources")
	if len(gotRes) != len(wantRes) {
		t.Fatalf("resource count = %d, Python = %d", len(gotRes), len(wantRes))
	}

	for i := range wantRes {
		g, w := asObject(t, gotRes[i]), asObject(t, wantRes[i])
		assertSameKeyOrder(t, "resources[%d]", g, w, i)
		// Identity fields must match exactly.
		for _, field := range []string{"id", "type", "name", "provider", "file_path", "line_number"} {
			gv, _ := g.Get(field)
			wv, _ := w.Get(field)
			if !reflect.DeepEqual(gv, wv) {
				t.Errorf("resources[%d].%s = %#v, Python = %#v", i, field, gv, wv)
			}
		}
		// Config: same keys in the same order; same VALUES wherever Python
		// produced something other than a pyhcl2 AST repr.
		gcfg, _ := g.Get("config")
		wcfg, _ := w.Get("config")
		id, _ := g.Get("id")
		compareIgnoringReprs(t, "resources["+pyfmt.Str(id)+"].config", gcfg, wcfg)
	}

	// The non-resource sections have no non-constant expressions on this
	// fixture, so they must be byte-identical.
	for _, section := range []string{"variables", "outputs", "providers", "modules"} {
		gv, _ := got.Get(section)
		wv, _ := want.Get(section)
		if !reflect.DeepEqual(gv, wv) {
			t.Errorf("%s = %#v, Python = %#v", section, gv, wv)
		}
	}
}

// Contract items 1-4 again, on the fixture that covers every HCL expression
// KIND rather than only the ones the benchmark repo happens to use.
func TestParseTerraformDirectory_MatchesPythonOnExpressionFixture(t *testing.T) {
	got, _, _, _ := parseFixture(t, expressionsFixtureDir)
	want := loadPythonFixture(t, pythonExpressionsFixt)

	assertSameKeyOrder(t, "$", got, want)

	for _, section := range []string{"resources", "variables", "outputs", "providers", "modules"} {
		g := sectionOf(t, got, section)
		w := sectionOf(t, want, section)
		if len(g) != len(w) {
			t.Fatalf("%s: %d entries, Python = %d", section, len(g), len(w))
		}
		for i := range w {
			path := section + "[" + itoa(i) + "]"
			if section != "resources" {
				compareIgnoringReprs(t, path, g[i], w[i])
				continue
			}
			// references/referenced_by are DERIVED from the config strings, so
			// they inherit the expression-rendering divergence: Go sees the
			// real traversals Python's AST reprs hide. They are asserted as a
			// superset here and exactly in
			// TestParseTerraformDirectory_ReferencesOnVulnerableInfra.
			gr, wr := asObject(t, g[i]), asObject(t, w[i])
			assertSameKeyOrder(t, "%s", gr, wr, path)
			for _, kv := range wr {
				gv, present := gr.Get(kv.K)
				if !present {
					t.Errorf("%s.%s: missing in the Go output", path, kv.K)
					continue
				}
				if kv.K == "references" || kv.K == "referenced_by" {
					assertSuperset(t, path+"."+kv.K, stringsOf(gv), stringsOf(kv.V))
					continue
				}
				compareIgnoringReprs(t, path+"."+kv.K, gv, kv.V)
			}
		}
	}
}

// assertSuperset checks that Go still reports everything Python did — the
// expression-rendering divergence is additive, never subtractive.
func assertSuperset(t *testing.T, path string, got, want []string) {
	t.Helper()
	for _, w := range want {
		if !contains(got, w) {
			t.Errorf("%s: Go dropped %q, which Python reports (got %v)", path, w, got)
		}
	}
}

// The documented divergence, pinned so it cannot grow silently: these — and
// ONLY these — are the leaves where Python emits a pyhcl2 AST repr and Go emits
// the expression's source text.
func TestParseTerraformDirectory_ExpressionRenderingDivergenceIsExactlyThis(t *testing.T) {
	cases := []struct {
		fixture string
		python  string
		want    []string
	}{
		{vulnerableInfraFixture, pythonInventoryFixture, []string{
			"resources[0].config.iam_instance_profile",
			"resources[0].config.vpc_security_group_ids[0]",
			"resources[2].config.assume_role_policy",
			"resources[3].config.role",
			"resources[4].config.role",
			"resources[4].config.policy",
			"resources[6].config.bucket",
		}},
		{expressionsFixtureDir, pythonExpressionsFixt, []string{
			"resources[0].config.neg",
			"resources[0].config.cond",
			"resources[0].config.fn",
			"resources[0].config.nullv",
			"resources[0].config.ref_list[0]",
			"resources[0].config.local_ref",
			"resources[0].config.var_ref",
			"resources[0].config.each_ref",
			"variables[0].type",
			"variables[1].type",
			"variables[2].type",
			"outputs[0].value",
		}},
	}

	for _, tc := range cases {
		t.Run(tc.fixture, func(t *testing.T) {
			got, _, _, _ := parseFixture(t, tc.fixture)
			want := loadPythonFixture(t, tc.python)

			var divergent []string
			collectReprPaths(&divergent, "", want)
			sort.Strings(divergent)
			expected := append([]string(nil), tc.want...)
			sort.Strings(expected)
			if !reflect.DeepEqual(divergent, expected) {
				t.Fatalf("pyhcl2-repr leaves in the Python fixture:\n got: %v\nwant: %v", divergent, expected)
			}

			// Every one of them must be a plain, repr-free value in Go.
			for _, path := range divergent {
				v := lookupPath(t, got, path)
				if s, ok := v.(string); ok && strings.Contains(s, pyhcl2ReprMarker) {
					t.Errorf("%s still contains a pyhcl2 repr in the Go output: %q", path, s)
				}
			}
		})
	}
}

// Contract item 5, spelled out per resource: Go's reference set is a SUPERSET of
// Python's on this fixture — it keeps the accidental matches Python finds inside
// string literals and adds the real traversals Python's AST reprs hid.
func TestParseTerraformDirectory_ReferencesOnVulnerableInfra(t *testing.T) {
	got, _, _, _ := parseFixture(t, vulnerableInfraFixture)
	want := loadPythonFixture(t, pythonInventoryFixture)

	goWant := map[string][]string{
		// "t2.micro" comes from the instance_type STRING LITERAL — Python finds
		// it too. The other two are the real traversals.
		"aws_instance.web_server": {
			"aws_iam_instance_profile.web_profile",
			"aws_security_group.allow_all",
			"t2.micro",
		},
		"aws_security_group.allow_all": {},
		// "ec2.amazonaws" comes from the "ec2.amazonaws.com" literal inside the
		// jsonencode() argument; both sides find it.
		"aws_iam_role.web_role":                {"ec2.amazonaws"},
		"aws_iam_instance_profile.web_profile": {"aws_iam_role.web_role"},
		"aws_iam_role_policy.s3_full_access": {
			"aws_iam_role.web_role",
			"aws_s3_bucket.customer_data",
		},
		"aws_s3_bucket.customer_data":                           {},
		"aws_s3_bucket_public_access_block.customer_data_block": {"aws_s3_bucket.customer_data"},
	}

	gotRes := sectionOf(t, got, "resources")
	wantRes := sectionOf(t, want, "resources")
	for i := range gotRes {
		g, w := asObject(t, gotRes[i]), asObject(t, wantRes[i])
		id := pyfmt.Str(mustGet(t, g, "id"))

		gotRefs := stringsOf(mustGet(t, g, "references"))
		if expected, ok := goWant[id]; !ok {
			t.Errorf("unexpected resource %q", id)
		} else if !reflect.DeepEqual(gotRefs, expected) {
			t.Errorf("%s references = %v, want %v", id, gotRefs, expected)
		}

		// Whatever Python found must still be found: the divergence is
		// additive, never subtractive.
		for _, pyRef := range stringsOf(mustGet(t, w, "references")) {
			if !contains(gotRefs, pyRef) {
				t.Errorf("%s: Go dropped the reference %q that Python reports", id, pyRef)
			}
		}
	}

	// referenced_by is the exact reverse index of references.
	reverse := map[string][]string{}
	for _, r := range gotRes {
		obj := asObject(t, r)
		id := pyfmt.Str(mustGet(t, obj, "id"))
		for _, ref := range stringsOf(mustGet(t, obj, "references")) {
			reverse[ref] = append(reverse[ref], id)
		}
	}
	for _, r := range gotRes {
		obj := asObject(t, r)
		id := pyfmt.Str(mustGet(t, obj, "id"))
		got := stringsOf(mustGet(t, obj, "referenced_by"))
		want := reverse[id]
		if want == nil {
			want = []string{}
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s referenced_by = %v, want %v", id, got, want)
		}
	}
}

// Contract item 4, as a table straight out of _PROVIDER_MAP.
func TestProviderFromType(t *testing.T) {
	cases := map[string]string{
		"aws_s3_bucket":              "aws",
		"azurerm_storage_account":    "azure",
		"azuread_application":        "azure",
		"google_storage_bucket":      "gcp",
		"kubernetes_deployment":      "kubernetes",
		"helm_release":               "kubernetes",
		"oci_core_instance":          "oci",
		"alicloud_instance":          "alicloud",
		"unknownprovider_thing":      "unknownprovider",
		"nounderscore":               "nounderscore", // no "_" -> the whole type
		"aws":                        "aws",
		"_leading":                   "", // split("_")[0] is ""
		"aws_iam_role_policy_attach": "aws",
	}
	for in, want := range cases {
		if got := providerFromType(in); got != want {
			t.Errorf("providerFromType(%q) = %q, want %q", in, got, want)
		}
	}
}

// Contract item 5, in isolation.
func TestExtractReferences(t *testing.T) {
	cases := []struct {
		name  string
		input any
		want  []string
	}{
		{"plain traversal", "aws_s3_bucket.b.arn", []string{"aws_s3_bucket.b"}},
		{"data traversal", "data.aws_ami.ubuntu.id", []string{"data.aws_ami.ubuntu"}},
		{
			"excluded namespaces",
			"var.x local.y each.key self.id count.index path.module terraform.workspace",
			[]string{},
		},
		{
			// Every namespace prefix is excluded by startswith, so a nested
			// var.-prefixed name is excluded too.
			"namespace prefix match is a prefix test",
			"var.something_long",
			[]string{},
		},
		{"uppercase is not a reference", "AWS_S3.Bucket", []string{}},
		{"digits may not lead", "1abc.def", []string{}},
		{"sorted and deduplicated", "b_x.y a_x.y b_x.y", []string{"a_x.y", "b_x.y"}},
		{"nested containers are walked", pyfmt.Ordered{
			{K: "a", V: []any{"aws_s3_bucket.one.id"}},
			{K: "b", V: pyfmt.Ordered{{K: "c", V: "aws_iam_role.two.arn"}}},
			{K: "d", V: 1},
			{K: "e", V: nil},
			{K: "f", V: true},
		}, []string{"aws_iam_role.two", "aws_s3_bucket.one"}},
		{
			// The literal-string quirk that makes Python report "t2.micro".
			"a dotted literal is indistinguishable from a reference",
			"t2.micro",
			[]string{"t2.micro"},
		},
		{
			// The regex stops at the second component, so a three-part
			// traversal contributes only "<type>.<name>".
			"three-part traversal yields two parts",
			"aws_s3_bucket.customer_data.arn",
			[]string{"aws_s3_bucket.customer_data"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := extractReferences(tc.input); !reflect.DeepEqual(got, tc.want) {
				t.Errorf("extractReferences = %v, want %v", got, tc.want)
			}
		})
	}
}

// Contract item 1: pathlib ordering is component-wise, and rglob does not skip
// dot-directories.
func TestTerraformFiles_PathlibOrderAndHiddenDirectories(t *testing.T) {
	root := t.TempDir()
	for _, rel := range []string{
		"probe.tf", "sub/s.tf", ".hidden/h.tf", "_under/u.tf",
		"a-b/c.tf", "a/b.tf", "not-terraform.txt", "deep/er/x.tf",
	} {
		full := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o777); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte("# tf\n"), 0o666); err != nil {
			t.Fatal(err)
		}
	}

	got, err := terraformFiles(root)
	if err != nil {
		t.Fatalf("terraformFiles: %v", err)
	}
	// sorted(Path(root).rglob("*.tf")) on Python 3.11 — component-wise, so
	// "a/b.tf" precedes "a-b/c.tf" even though the raw strings sort the other
	// way ('-' < '/').
	want := []string{
		".hidden/h.tf",
		"_under/u.tf",
		"a/b.tf",
		"a-b/c.tf",
		"deep/er/x.tf",
		"probe.tf",
		"sub/s.tf",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("terraformFiles = %v\n                want %v", got, want)
	}
}

// Contract item 1: a missing repo path yields an empty inventory, matching
// pathlib.rglob rather than raising.
func TestParseTerraformDirectory_MissingRepoIsEmptyNotFatal(t *testing.T) {
	out := t.TempDir()
	path, total, iacType, err := ParseTerraformDirectory(filepath.Join(t.TempDir(), "nope"), out)
	if err != nil {
		t.Fatalf("want no error for a missing repo, got %v", err)
	}
	if total != 0 || iacType != "terraform" {
		t.Errorf("got (%d, %q), want (0, \"terraform\")", total, iacType)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "{\n  \"resources\": [],\n  \"variables\": [],\n  \"outputs\": [],\n  \"providers\": [],\n  \"modules\": []\n}"
	if string(raw) != want {
		t.Errorf("empty inventory =\n%s\nwant\n%s", raw, want)
	}
}

// Contract item 7.
func TestParseTerraformDirectory_SkipsUnparsableFiles(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "broken.tf"), []byte("resource \"a\" {{{\n"), 0o666); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "ok.tf"), []byte("resource \"aws_s3_bucket\" \"b\" {\n  bucket = \"x\"\n}\n"), 0o666); err != nil {
		t.Fatal(err)
	}

	out := t.TempDir()
	_, total, _, err := ParseTerraformDirectory(root, out)
	if err != nil {
		t.Fatalf("an unparsable file must not be fatal: %v", err)
	}
	if total != 1 {
		t.Errorf("total = %d, want 1 (the good file only)", total)
	}
}

// Contract item 2: labels below the required arity are ignored entirely.
func TestParseTerraformDirectory_IgnoresUnderLabelledBlocks(t *testing.T) {
	root := t.TempDir()
	src := `
resource "aws_s3_bucket" {
  bucket = "no-name-label"
}
data "aws_ami" {
  most_recent = true
}
variable {
  type = string
}
locals {
  x = 1
}
terraform {
  required_version = ">= 1.0"
}
`
	if err := os.WriteFile(filepath.Join(root, "main.tf"), []byte(src), 0o666); err != nil {
		t.Fatal(err)
	}
	got, _, total, _ := parseFixture(t, root)
	if total != 0 {
		t.Errorf("total = %d, want 0", total)
	}
	for _, section := range []string{"resources", "variables", "outputs", "providers", "modules"} {
		if entries := sectionOf(t, got, section); len(entries) != 0 {
			t.Errorf("%s = %v, want empty", section, entries)
		}
	}
}

// Contract item 3: the str()/raw asymmetries between the four non-resource
// record kinds.
func TestParseTerraformDirectory_NonResourceRecordShapes(t *testing.T) {
	got, _, _, _ := parseFixture(t, expressionsFixtureDir)

	variables := sectionOf(t, got, "variables")
	v0 := asObject(t, variables[1]) // variable "count_n" { type = number, default = 3 }
	if v, _ := v0.Get("default"); v != "3" {
		t.Errorf(`variable.default = %#v, want the STRING "3" (Python str()s it)`, v)
	}
	if v, _ := v0.Get("description"); v != nil {
		t.Errorf("variable.description = %#v, want nil (absent, and NOT str()-ed)", v)
	}
	v2 := asObject(t, variables[2]) // variable "no_default" — no default at all
	if v, _ := v2.Get("default"); v != nil {
		t.Errorf("a missing variable default must stay nil, got %#v", v)
	}

	outputs := sectionOf(t, got, "outputs")
	o1 := asObject(t, outputs[1])
	if v, _ := o1.Get("value"); v != "hello" {
		t.Errorf("output.value = %#v, want %q", v, "hello")
	}
	if v, _ := o1.Get("description"); v != nil {
		t.Errorf("output.description = %#v, want nil", v)
	}

	providers := sectionOf(t, got, "providers")
	p0 := asObject(t, providers[0])
	if v, _ := p0.Get("version"); v != nil {
		t.Error("provider.version must always be nil — the parser never reads one")
	}
	if v, _ := p0.Get("alias"); v != "second" {
		t.Errorf("provider.alias = %#v, want %q", v, "second")
	}

	modules := sectionOf(t, got, "modules")
	m0 := asObject(t, modules[0])
	if v, _ := m0.Get("version"); v != "3.0.0" {
		t.Errorf("module.version = %#v, want %q", v, "3.0.0")
	}
}

// Nested-block collapsing: labeled -> map keyed by the label, unlabeled repeats
// -> a list, single unlabeled -> a bare object.
func TestBlockToDict_NestedBlockCollapsing(t *testing.T) {
	got, _, _, _ := parseFixture(t, expressionsFixtureDir)
	cfg := asObject(t, mustGet(t, asObject(t, sectionOf(t, got, "resources")[0]), "config"))

	versioning, _ := cfg.Get("versioning")
	if _, ok := versioning.(pyfmt.Ordered); !ok {
		t.Errorf("a single unlabeled block must be an object, got %T", versioning)
	}

	ingress, _ := cfg.Get("ingress")
	list, ok := ingress.([]any)
	if !ok || len(list) != 2 {
		t.Fatalf("repeated unlabeled blocks must collapse into a 2-element list, got %#v", ingress)
	}
	if v, _ := asObject(t, list[0]).Get("from_port"); v != 1 {
		t.Errorf("ingress[0].from_port = %#v, want 1", v)
	}
	if v, _ := asObject(t, list[1]).Get("from_port"); v != 2 {
		t.Errorf("ingress[1].from_port = %#v, want 2", v)
	}

	dyn, _ := cfg.Get("dynamic")
	dynObj, ok := dyn.(pyfmt.Ordered)
	if !ok {
		t.Fatalf("a labeled block must be keyed by its label, got %T", dyn)
	}
	if _, ok := dynObj.Get("rule"); !ok {
		t.Errorf(`dynamic block must be keyed "rule", got %v`, dynObj)
	}
}

// The Go copy of the Terraform fixture must not drift from the one the Python
// tests use.
func TestVulnerableInfraFixture_MatchesThePythonTree(t *testing.T) {
	pythonCopy, err := os.ReadFile(pythonTreeInfraRelative)
	if err != nil {
		t.Skipf("Python tree not present in this checkout: %v", err)
	}
	goCopy, err := os.ReadFile(filepath.Join(vulnerableInfraFixture, "main.tf"))
	if err != nil {
		t.Fatal(err)
	}
	if string(goCopy) != string(pythonCopy) {
		t.Error("testdata/vulnerable_infra/main.tf has drifted from tests/fixtures/vulnerable_infra/main.tf; rerun go/scripts/gen_golden.py")
	}
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func sectionOf(t *testing.T, o pyfmt.Ordered, key string) []any {
	t.Helper()
	v, ok := o.Get(key)
	if !ok {
		t.Fatalf("missing section %q", key)
	}
	items, ok := v.([]any)
	if !ok {
		t.Fatalf("section %q is %T, want a list", key, v)
	}
	return items
}

func asObject(t *testing.T, v any) pyfmt.Ordered {
	t.Helper()
	o, ok := v.(pyfmt.Ordered)
	if !ok {
		t.Fatalf("value is %T, want an object", v)
	}
	return o
}

func assertSameKeyOrder(t *testing.T, format string, got, want pyfmt.Ordered, args ...any) {
	t.Helper()
	gk := make([]string, len(got))
	for i, kv := range got {
		gk[i] = kv.K
	}
	wk := make([]string, len(want))
	for i, kv := range want {
		wk[i] = kv.K
	}
	if !reflect.DeepEqual(gk, wk) {
		t.Errorf(format+": key order = %v, Python = %v", append(args, gk, wk)...)
	}
}

// compareIgnoringReprs asserts Go and Python agree everywhere except at the
// leaves where Python emitted a pyhcl2 AST repr.
func compareIgnoringReprs(t *testing.T, path string, got, want any) {
	t.Helper()
	if s, ok := want.(string); ok && strings.Contains(s, pyhcl2ReprMarker) {
		return // documented divergence; pinned separately
	}
	switch w := want.(type) {
	case pyfmt.Ordered:
		g, ok := got.(pyfmt.Ordered)
		if !ok {
			t.Errorf("%s: Go value is %T, Python has an object", path, got)
			return
		}
		assertSameKeyOrder(t, "%s", g, w, path)
		for _, kv := range w {
			gv, present := g.Get(kv.K)
			if !present {
				t.Errorf("%s.%s: missing in the Go output", path, kv.K)
				continue
			}
			compareIgnoringReprs(t, path+"."+kv.K, gv, kv.V)
		}
	case []any:
		g, ok := got.([]any)
		if !ok {
			t.Errorf("%s: Go value is %T, Python has a list", path, got)
			return
		}
		if len(g) != len(w) {
			t.Errorf("%s: %d elements, Python has %d", path, len(g), len(w))
			return
		}
		for i := range w {
			compareIgnoringReprs(t, path+"["+itoa(i)+"]", g[i], w[i])
		}
	default:
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s = %#v, Python = %#v", path, got, want)
		}
	}
}

// collectReprPaths records every leaf of the Python fixture whose value is a
// pyhcl2 AST repr.
func collectReprPaths(out *[]string, path string, v any) {
	switch x := v.(type) {
	case pyfmt.Ordered:
		for _, kv := range x {
			child := kv.K
			if path != "" {
				child = path + "." + kv.K
			}
			collectReprPaths(out, child, kv.V)
		}
	case []any:
		for i, item := range x {
			collectReprPaths(out, path+"["+itoa(i)+"]", item)
		}
	case string:
		if strings.Contains(x, pyhcl2ReprMarker) {
			*out = append(*out, path)
		}
	}
}

// lookupPath resolves a dotted/indexed path produced by collectReprPaths.
func lookupPath(t *testing.T, root pyfmt.Ordered, path string) any {
	t.Helper()
	var cur any = root
	for _, seg := range strings.Split(path, ".") {
		name, indices := splitIndices(seg)
		if name != "" {
			obj, ok := cur.(pyfmt.Ordered)
			if !ok {
				t.Fatalf("%s: %q is not an object", path, name)
			}
			v, present := obj.Get(name)
			if !present {
				t.Fatalf("%s: key %q missing", path, name)
			}
			cur = v
		}
		for _, idx := range indices {
			list, ok := cur.([]any)
			if !ok || idx >= len(list) {
				t.Fatalf("%s: index %d out of range", path, idx)
			}
			cur = list[idx]
		}
	}
	return cur
}

func splitIndices(seg string) (string, []int) {
	open := strings.IndexByte(seg, '[')
	if open < 0 {
		return seg, nil
	}
	name := seg[:open]
	var indices []int
	rest := seg[open:]
	for len(rest) > 0 && rest[0] == '[' {
		close := strings.IndexByte(rest, ']')
		if close < 0 {
			break
		}
		n := 0
		for _, c := range rest[1:close] {
			n = n*10 + int(c-'0')
		}
		indices = append(indices, n)
		rest = rest[close+1:]
	}
	return name, indices
}

func stringsOf(v any) []string {
	items, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, it := range items {
		if s, ok := it.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}

// TestParseTerraformDirectory_IntegerLiteralsKeepPythonsExactDigits pins the
// arbitrary-precision half of Python's int.
//
// pyhcl2 evaluates an integer literal into `Integer._raw`, a Python int, and
// `json.dump` writes its exact digits however large it is. Ground truth from
// the repo venv on this exact fixture:
//
//	"big_port": 12345678901234567890,
//	"edge_hi":  9223372036854775807,
//	"edge_ovr": 9223372036854775808,
//	"small":    5432,
//	"floaty":   1.5
//
// Converting through float64 (what `bf.Float64()` does) wrote
// 1.2345678901234567e+19 and 9.223372036854776e+18 instead — and because
// "port" is a configSummaryKeywords match, the lossy value also reached
// graph.json's config_summary and the hunter prompt's `Config: {...}` line.
func TestParseTerraformDirectory_IntegerLiteralsKeepPythonsExactDigits(t *testing.T) {
	root := t.TempDir()
	src := `resource "aws_s3_bucket" "b" {
  bucket   = "x"
  big_port = 12345678901234567890
  edge_hi  = 9223372036854775807
  edge_ovr = 9223372036854775808
  small    = 5432
  floaty   = 1.5
}
`
	if err := os.WriteFile(filepath.Join(root, "main.tf"), []byte(src), 0o666); err != nil {
		t.Fatal(err)
	}

	out := t.TempDir()
	path, _, _, err := ParseTerraformDirectory(root, out)
	if err != nil {
		t.Fatalf("ParseTerraformDirectory: %v", err)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read inventory.json: %v", err)
	}
	text := string(raw)
	for _, want := range []string{
		`"big_port": 12345678901234567890`,
		`"edge_hi": 9223372036854775807`,
		`"edge_ovr": 9223372036854775808`,
		`"small": 5432`,
		`"floaty": 1.5`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("inventory.json is missing %s\ngot:\n%s", want, text)
		}
	}
	if strings.Contains(text, "e+19") || strings.Contains(text, "e+18") {
		t.Errorf("an integer literal was written as a float:\n%s", text)
	}

	// The read side has to agree, or the value degrades on its way into
	// graph.json's config_summary and the hunter prompt.
	reloaded, err := pyfmt.Load(raw)
	if err != nil {
		t.Fatalf("pyfmt.Load: %v", err)
	}
	config := configOfFirstResource(t, reloaded)
	big, _ := config.Get("big_port")
	if got := pyfmt.Repr(big); got != "12345678901234567890" {
		t.Errorf("repr(config[\"big_port\"]) = %s, want the exact digits", got)
	}
	if got := pyfmt.Dumps(config, 0); !strings.Contains(got, `"big_port": 12345678901234567890`) {
		t.Errorf("re-dumping the loaded config lost the digits: %s", got)
	}
}

func configOfFirstResource(t *testing.T, decoded any) pyfmt.Ordered {
	t.Helper()
	obj, ok := decoded.(pyfmt.Ordered)
	if !ok {
		t.Fatalf("inventory decoded as %T", decoded)
	}
	resources, _ := obj.Get("resources")
	list, ok := resources.([]any)
	if !ok || len(list) == 0 {
		t.Fatalf("resources = %#v", resources)
	}
	first, ok := list[0].(pyfmt.Ordered)
	if !ok {
		t.Fatalf("resources[0] = %T", list[0])
	}
	config, _ := first.Get("config")
	cfg, ok := config.(pyfmt.Ordered)
	if !ok {
		t.Fatalf("config = %T", config)
	}
	return cfg
}

// TestParseTerraformDirectory_ParserAcceptanceDivergesFromPyhcl2 pins the
// whole-file divergence documented on ParseTerraformDirectory.
//
// Both nodes skip a .tf file their parser rejects, but the two parsers disagree
// about WHICH files those are. Measured against pyhcl2 in the repo venv:
//
//	parse_file("resource \"a\" \"b\" { p = 1e3 }")     -> DiagnosticError
//	parse_file("resource \"a\" \"b\" { p = 1E3 }")     -> DiagnosticError
//	parse_file("resource \"a\" \"b\" { p = 1.5e-3 }")  -> DiagnosticError
//	parse_file("resource \"a\" \"b\" { p = 1000 }")    -> OK
//
// so for the exponent files Python emits an EMPTY inventory while Go emits the
// resource. Go is the better behaviour (the spellings are valid HCL); this test
// exists so the divergence is a recorded, deliberate one rather than something
// a reviewer diffing two inventories has to rediscover.
func TestParseTerraformDirectory_ParserAcceptanceDivergesFromPyhcl2(t *testing.T) {
	for _, literal := range []string{"1e3", "1E3", "1.5e-3"} {
		root := t.TempDir()
		src := "resource \"aws_s3_bucket\" \"b\" {\n  p = " + literal + "\n}\n"
		if err := os.WriteFile(filepath.Join(root, "main.tf"), []byte(src), 0o666); err != nil {
			t.Fatal(err)
		}
		_, total, _, err := ParseTerraformDirectory(root, t.TempDir())
		if err != nil {
			t.Fatalf("%s: %v", literal, err)
		}
		if total != 1 {
			t.Errorf("p = %s -> total = %d, want 1 (hclsyntax accepts exponents; "+
				"pyhcl2 rejects them and Python drops the whole file)", literal, total)
		}
	}
}
